# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#   name = "Blog"
#   pageRef = "posts"
#   weight = 10

[[main]]
  name = "Propuesta"
  pageRef = "propuesta"
  weight = 10


[[main]]
    name = "Proyectos"
    pageRef = "proyectos"
    weight = 11

[[main]]
  name = "Conceptos"
  pageRef = "conceptos"
  weight = 12

[[main]]
  name = "Roadmap"
  url = "https://kan.neyzt.org/openutt/iniciativa"
  weight = 21
  [main.params]
      target = "_blank"

[[main]]
    name = "GitHub"
    url = "https://github.com/openutt"
    weight = 25
    [main.params]
        icon = "github"
        showName = false
        target = "_blank"

[[main]]
    name = "Discord"
    url = "https://discord.gg/A92Gc7jBC2"
    weight = 26
    [main.params]
        icon = "discord"
        showName = false
        target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Mira los repositorios"
  url = "https://github.com/openutt"
  weight = 10
  [footer.params]
      icon = "github"
      target = "_blank"

[[footer]]
    name = "Unete a la comunidad"
    url = "https://discord.gg/A92Gc7jBC2"
    weight = 12
    [footer.params]
        icon = "discord"
        target = "_blank"

[[footer]]
    name = "Mira el estado de la iniciativa"
    url = "https://kan.neyzt.org/openutt/iniciativa"
    weight = 13
    [footer.params]
        icon = "list"
        target = "_blank"
